include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    curly_braces_in_flow_control_structures: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true


analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
    # Enable one rule
    - provider_parameters
    # Disable another
    - missing_provider_scope: true #False positive